name: run-collector-daily
on:
  schedule:
    - cron: '0 16 * * *'   # 매일 01:00 JST (UTC 16:00)
  workflow_dispatch: {}
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      
      - name: Run daily collector (PyKRX)
        run: python collector_v1.py
        env:
          SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
          SLEEP_SEC: '0.5'
      
      - name: Run financial collector (OpenDart)
        run: python collector_dart.py
        env:
          SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
